#!/bin/tcsh -f

# ============================================================================
# Configure Julia + system MPI for ClimaAtmos on LRZ terrabyte.
#
#   usage:  ./runscripts/setup-julia-terrabyte.tcsh cpu
#
# This is the terrabyte sibling of setup-julia-levante.tcsh. Read that script
# for the reasoning the two machines share, which is most of it:
#
#   - HDF5_jll, NetCDF_jll and TempestRemap_jll all `using OpenMPI_jll`, whose
#     __init__ dlopens its own bundled libmpi whatever MPIPreferences says. An
#     artifact override is the only thing that fixes the resulting collision,
#     so the depot gets an artifacts/Overrides.toml pointing OpenMPI_jll at the
#     system installation.
#   - The MPI preference is written directly rather than through
#     MPIPreferences.use_system_binary(), which probes by dlopen and so breaks
#     exactly when you are switching away from another MPI. That is our case
#     here: the preferences file may still name Levante's libmpi.
#   - All preferences go to .buildkite/LocalPreferences.toml, leaving
#     .buildkite/Project.toml alone.
#
# What differs from Levante, and why
# ----------------------------------
# `module purge` is NOT run here. On Levante it is load-bearing. On terrabyte it
# is destructive: it drops stack/24.4.0, after which the spack modules are not
# found, and re-loading stack does not repair it. A clean login shell already
# carries only stack/24.4.0, so there is nothing to clear. Any MPI module that
# is loaded gets an explicit `module unload` instead.
#
# The depot lives on scratch, not under $HOME. $HOME on terrabyte is for code
# and configs. See runscripts/terrabyte_stacks.env.
#
# Only the cpu stack is supported. terrabyte has GPU nodes and nvhpc/24.9 ships
# a CUDA-aware Open MPI, but nothing has been verified on a GPU node and the
# CUDA toolkit pin needs a driver version measured there. The module pairing is
# recorded in terrabyte_stacks.env for whoever does that work.
#
# .buildkite/LocalPreferences.toml is generated by this script and is not
# tracked in git. A checkout carries no libmpi path with it, which is what used
# to break the other machine.
# ============================================================================

# ----------------------------------------------------------------------------
# Locate the repository from this script, rather than hardcoding a path. The
# script lives in <root>/runscripts/.
# ----------------------------------------------------------------------------

set SCRIPT_SELF = $0
set SCRIPT_DIR  = `dirname "${SCRIPT_SELF}"`
set SCRIPT_DIR  = `cd "${SCRIPT_DIR}" && pwd`
set ROOT        = `dirname "${SCRIPT_DIR}"`
set PROJECT     = ${ROOT}/.buildkite

# Julia. juliaup is on PATH from ~/.juliaup/bin. Naming the channel keeps the
# version explicit rather than inheriting whatever the default channel is.
if ($?TERRABYTE_JULIA) then
    set JULIA_BIN = "${TERRABYTE_JULIA}"
else
    set JULIA_BIN = ${HOME}/.juliaup/bin/julia
endif
set JULIA_CHANNEL = +1.11

# OpenMPI_jll's UUID, from .buildkite/Manifest-v1.11.toml
set OPENMPI_JLL_UUID = fe0851c0-eecd-5654-98d4-656369965a5c

set STACKS_ENV = ${ROOT}/runscripts/terrabyte_stacks.env

if (! -r "${STACKS_ENV}") then
    echo "ERROR: stack definitions not found: ${STACKS_ENV}"
    exit 1
endif

# ----------------------------------------------------------------------------
# Stack selection
# ----------------------------------------------------------------------------

if ($#argv != 1) then
    echo "usage: $0 cpu"
    exit 1
endif

set STACK = $argv[1]

if ("${STACK}" == "gpu") then
    echo "ERROR: the gpu stack is not set up on terrabyte yet."
    echo
    echo "The pieces are identified but unverified. See the commented GPU keys"
    echo "in ${STACKS_ENV}: nvhpc/24.9 carries a CUDA-aware Open MPI 4.1.5, and"
    echo "the GPU partitions are hpda2_compute_gpu and hpda2_testgpu."
    echo
    echo "Finishing it means measuring the driver's CUDA version on a GPU node"
    echo "and pinning CUDA_Runtime_jll with runscripts/select-cuda-runtime.jl,"
    echo "the way setup-julia-levante.tcsh does."
    exit 1
endif

if ("${STACK}" != "cpu") then
    echo "ERROR: unknown stack '${STACK}' (expected cpu)"
    exit 1
endif

# Read this stack's definition out of ${STACKS_ENV}. The keys are prefixed with
# the upper-cased stack name, e.g. TERRABYTE_CPU_MPI_MODULE.
set STACK_UC = `echo "${STACK}" | tr '[:lower:]' '[:upper:]'`

set COMPILER_MODULE = `sed -n "s/^TERRABYTE_${STACK_UC}_COMPILER_MODULE=//p" "${STACKS_ENV}"`
set MPI_MODULE      = `sed -n "s/^TERRABYTE_${STACK_UC}_MPI_MODULE=//p" "${STACKS_ENV}"`
set DEPOT_NAME      = `sed -n "s/^TERRABYTE_${STACK_UC}_DEPOT_NAME=//p" "${STACKS_ENV}"`
set SRUN_MPI        = `sed -n "s/^TERRABYTE_${STACK_UC}_SRUN_MPI=//p" "${STACKS_ENV}"`

if ("${COMPILER_MODULE}" == "" || "${MPI_MODULE}" == "" || \
    "${DEPOT_NAME}" == "" || "${SRUN_MPI}" == "") then
    echo "ERROR: ${STACKS_ENV} does not define the '${STACK}' stack completely."
    echo "Expected TERRABYTE_${STACK_UC}_{COMPILER_MODULE,MPI_MODULE,DEPOT_NAME,SRUN_MPI}."
    exit 1
endif

# Parent directory for the per-stack depots. Each holds a full copy of the
# packages, artifacts and precompile cache, running to several GB, which is why
# the default is on scratch rather than under $HOME.
if ($?TERRABYTE_DEPOT_ROOT) then
    set DEPOT_ROOT = "${TERRABYTE_DEPOT_ROOT}"
else
    set DEPOT_ROOT = `sed -n 's/^TERRABYTE_DEPOT_ROOT_ABSOLUTE=//p' "${STACKS_ENV}"`
endif

if ("${DEPOT_ROOT}" == "") then
    echo "ERROR: no depot root. Set TERRABYTE_DEPOT_ROOT, or define"
    echo "TERRABYTE_DEPOT_ROOT_ABSOLUTE in ${STACKS_ENV}."
    exit 1
endif

set DEPOT = ${DEPOT_ROOT}/${DEPOT_NAME}

echo "============================================================"
echo "ClimaAtmos Julia setup on terrabyte -- ${STACK}"
echo "============================================================"
echo "Repository: ${ROOT}"
echo "Project:    ${PROJECT}"
echo "Julia:      ${JULIA_BIN} ${JULIA_CHANNEL}"
echo "Depot:      ${DEPOT}"
echo "Compiler:   ${COMPILER_MODULE}"
echo "MPI:        ${MPI_MODULE}"
echo

if (! -x "${JULIA_BIN}") then
    echo "ERROR: Julia executable not found: ${JULIA_BIN}"
    echo "Set TERRABYTE_JULIA to its path, or install juliaup."
    exit 1
endif

if (! -f "${PROJECT}/Project.toml") then
    echo "ERROR: Project.toml not found: ${PROJECT}/Project.toml"
    exit 1
endif

# MPIPreferences and CUDA_Runtime_jll both have to be direct dependencies for
# their project-local preferences to be visible. Base.get_preferences maps the
# names in LocalPreferences.toml to UUIDs through the project's own deps, so a
# preference written for an indirect dependency is dropped in silence.
# CUDA_Runtime_jll arrives indirectly through CUDA, so it is listed explicitly.
# The cpu stack clears rather than writes the CUDA preference, but the check
# stays: a clear that is silently ignored leaves a stale pin behind.
#
# Check the dedicated .buildkite environment without resolving the repository
# root environment, whose dependency graph is unrelated here.
#
# The Julia below avoids the exclamation mark on purpose. tcsh performs history
# expansion before quoting, and single quotes leave it in force, so a `!`
# followed by a word character reads as a history reference. Negating
# haskey(...) that way aborts the whole script with "haskey: Event not found."
# before Julia starts, which is why this is a loop rather than a filter. Uses
# like pop!( and != elsewhere in this file are safe, since expansion needs a
# word character to follow.
${JULIA_BIN} ${JULIA_CHANNEL} --startup-file=no \
    -e 'using TOML; project = TOML.parsefile(ARGS[1]); deps = get(project, "deps", Dict()); for name in ARGS[2:end]; haskey(deps, name) || error(name * " is not a direct dependency"); end' \
    "${PROJECT}/Project.toml" MPIPreferences CUDA_Runtime_jll
if ($status != 0) then
    echo "ERROR: MPIPreferences and CUDA_Runtime_jll must both be listed in"
    echo "  ${PROJECT}/Project.toml"
    echo "Their preferences are otherwise written but never read back."
    exit 1
endif

# ----------------------------------------------------------------------------
# Modules
#
# No `module purge` here. See the header. A clean shell carries only
# stack/24.4.0, and purging it cannot be undone by re-loading stack.
# ----------------------------------------------------------------------------

if ($?MODULESHOME == 0) then
    echo "ERROR: MODULESHOME is unset, so the module system cannot be started."
    exit 1
endif

if (! -r "${MODULESHOME}/init/tcsh") then
    echo "ERROR: module init script not found: ${MODULESHOME}/init/tcsh"
    exit 1
endif

source ${MODULESHOME}/init/tcsh

which module >& /dev/null
if ($status != 0) then
    echo "ERROR: the 'module' command is unavailable after sourcing init/tcsh."
    exit 1
endif

# Drop any MPI already on the path. Two Open MPI builds in one process is the
# failure this whole script exists to prevent, and a leftover module is the
# easiest way to get one.
#
# The loaded modules are read from $LOADEDMODULES rather than from
# `module list`. Piping a module command does not work: `module` is an alias
# that expands to an eval, so the pipeline reports "Invalid null command" and
# yields nothing, which would silently skip every unload below.
if ($?LOADEDMODULES) then
    foreach loaded (`echo "${LOADEDMODULES}" | tr ':' '\n' | grep -E '^(openmpi|intel-mpi|nvhpc)/'`)
        echo "Unloading ${loaded}, which would collide with ${MPI_MODULE}."
        module unload ${loaded}
    end
endif

module load ${COMPILER_MODULE}
if ($status != 0) then
    echo "ERROR: could not load ${COMPILER_MODULE}"
    echo "Run 'module -t avail' and correct TERRABYTE_${STACK_UC}_COMPILER_MODULE"
    echo "in ${STACKS_ENV}."
    exit 1
endif

module load ${MPI_MODULE}
if ($status != 0) then
    echo "ERROR: could not load ${MPI_MODULE}"
    echo "Run 'module -t avail' and correct TERRABYTE_${STACK_UC}_MPI_MODULE"
    echo "in ${STACKS_ENV}."
    exit 1
endif

echo "Loaded modules:"
module list
echo

# ----------------------------------------------------------------------------
# Discover the system MPI
# ----------------------------------------------------------------------------

which mpicc >& /dev/null
if ($status != 0) then
    echo "ERROR: mpicc unavailable after loading ${MPI_MODULE}."
    exit 1
endif

set MPI_LIBDIRS = ( `mpicc --showme:libdirs` )
if ($#MPI_LIBDIRS < 1) then
    echo "ERROR: mpicc did not report an MPI library directory."
    exit 1
endif

set MPI_LIBDIR  = ${MPI_LIBDIRS[1]}
set MPI_PREFIX  = `dirname "${MPI_LIBDIR}"`
set MPI_LIBRARY = ${MPI_LIBDIR}/libmpi.so

if (! -e "${MPI_LIBRARY}") then
    echo "ERROR: MPI library not found: ${MPI_LIBRARY}"
    exit 1
endif

echo "MPI compiler: `which mpicc`"
mpicc --showme:version
echo "MPI prefix:   ${MPI_PREFIX}"
echo "MPI library:  ${MPI_LIBRARY}"
echo

# Confirm the library loads, which is a stronger check than the file existing.
# The failure happens at dlopen time and is far easier to diagnose here.
${JULIA_BIN} ${JULIA_CHANNEL} --startup-file=no \
    -e 'using Libdl; Libdl.dlopen(ARGS[1]); println("dlopen ok: ", ARGS[1])' "${MPI_LIBRARY}"
if ($status != 0) then
    echo "ERROR: ${MPI_LIBRARY} exists but could not be loaded."
    echo "Check: ldd ${MPI_LIBRARY} | grep 'not found'"
    exit 1
endif

echo "PMIx linkage of the system MPI:"
ldd "${MPI_LIBRARY}" |& grep -E "libpmix|libopen-pal" || true
echo

# ----------------------------------------------------------------------------
# Per-stack depot and the OpenMPI_jll override
# ----------------------------------------------------------------------------

setenv JULIA_DEPOT_PATH "${DEPOT}"
mkdir -p "${DEPOT}/artifacts"
if ($status != 0) then
    echo "ERROR: could not create the depot at ${DEPOT}"
    exit 1
endif

set OVERRIDES = ${DEPOT}/artifacts/Overrides.toml

cat > "${OVERRIDES}" << EOF
# Written by setup-julia-terrabyte.tcsh for the ${STACK} stack.
# Repoints OpenMPI_jll at terrabyte's system Open MPI so that HDF5_jll,
# NetCDF_jll and TempestRemap_jll load the same MPI as MPI.jl.
["${OPENMPI_JLL_UUID}"]
OpenMPI = "${MPI_PREFIX}"
EOF

echo "Wrote ${OVERRIDES}:"
cat "${OVERRIDES}"
echo

# ----------------------------------------------------------------------------
# Environment
# ----------------------------------------------------------------------------

setenv JULIA_NUM_THREADS 1
setenv OMP_NUM_THREADS 1
setenv OPENBLAS_NUM_THREADS 1
setenv MKL_NUM_THREADS 1

if ($?I_MPI_HYDRA_BOOTSTRAP) unsetenv I_MPI_HYDRA_BOOTSTRAP
if ($?I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS) unsetenv I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS
if ($?I_MPI_PMI) unsetenv I_MPI_PMI
if ($?I_MPI_PMI_LIBRARY) unsetenv I_MPI_PMI_LIBRARY

# ----------------------------------------------------------------------------
# Write the MPI preference directly.
#
# The recorded value is the extension-less path, the form MPIPreferences itself
# stores. The loader resolves libmpi.so from it.
# ----------------------------------------------------------------------------

setenv TERRABYTE_LIBMPI "${MPI_LIBDIR}/libmpi"
setenv TERRABYTE_PREFS "${PROJECT}/LocalPreferences.toml"

# Written as a one-liner instead of a here-document. tcsh handles a quoted
# here-document delimiter (<< 'EOF') unreliably and can write no file at all
# without saying so.
${JULIA_BIN} ${JULIA_CHANNEL} --startup-file=no -e 'using TOML; pf = ENV["TERRABYTE_PREFS"]; prefs = isfile(pf) ? TOML.parsefile(pf) : Dict{String,Any}(); prefs["MPIPreferences"] = Dict{String,Any}("_format" => "1.0", "abi" => "OpenMPI", "binary" => "system", "cclibs" => String[], "libmpi" => ENV["TERRABYTE_LIBMPI"], "mpiexec" => "srun", "preloads" => String[]); open(io -> TOML.print(io, prefs), pf, "w"); println("wrote MPI preferences to ", pf)'
if ($status != 0) then
    echo "ERROR: could not write MPI preferences."
    exit 1
endif

# Drop the entire CUDA preference table. The cpu stack installs no toolkit, and
# a leftover pin, such as the one a GPU setup on another machine leaves behind,
# would have this depot download one it never uses. This also clears an empty
# [CUDA_Runtime_jll] table, should one be present.
${JULIA_BIN} ${JULIA_CHANNEL} --startup-file=no \
    -e 'using TOML; pf = ENV["TERRABYTE_PREFS"]; prefs = isfile(pf) ? TOML.parsefile(pf) : Dict{String,Any}(); pop!(prefs, "CUDA_Runtime_jll", nothing); open(io -> TOML.print(io, prefs), pf, "w"); println("cleared CUDA runtime preferences from ", pf)'
if ($status != 0) then
    echo "ERROR: could not clear the CUDA toolkit pin."
    exit 1
endif

echo
echo "LocalPreferences.toml:"
cat "${TERRABYTE_PREFS}"
echo

# ----------------------------------------------------------------------------
# Instantiate and precompile into this depot
# ----------------------------------------------------------------------------

echo "Instantiating (slow on a fresh depot):"
${JULIA_BIN} ${JULIA_CHANNEL} --project="${PROJECT}" --startup-file=no \
    -e 'using Pkg; Pkg.instantiate()'
if ($status != 0) then
    echo "ERROR: instantiation failed."
    exit 1
endif

echo
echo "Precompiling (slow on a fresh depot):"
${JULIA_BIN} ${JULIA_CHANNEL} --project="${PROJECT}" --startup-file=no \
    -e 'using Pkg; Pkg.precompile()'
if ($status != 0) then
    echo "ERROR: precompilation failed."
    exit 1
endif

# ----------------------------------------------------------------------------
# Verification
#
# NCDatasets is loaded on purpose. NetCDF_jll depends on both HDF5_jll and
# OpenMPI_jll, so a bundled MPI can enter through NetCDF while MPI.jl and
# HDF5.jl both look clean.
# ----------------------------------------------------------------------------

echo
echo "============================================================"
echo "Verification"
echo "============================================================"

${JULIA_BIN} ${JULIA_CHANNEL} --project="${PROJECT}" --startup-file=no \
    -e 'using MPI, HDF5, NCDatasets, Libdl; MPI.versioninfo(); println("parallel HDF5: ", HDF5.has_parallel()); libs = filter(p -> occursin(r"libmpi|libopen-pal|libpmix|libhdf5|libnetcdf", basename(p)), Libdl.dllist()); println("loaded MPI/HDF5/NetCDF libraries:"); foreach(p -> println("  ", p), libs); HDF5.has_parallel() || error("HDF5 lacks parallel support"); bad = filter(p -> occursin("/artifacts/", p) && occursin(r"libmpi|libopen-pal|libpmix", basename(p)), libs); isempty(bad) || error("a bundled MPI library is still loaded: " * join(bad, ", "))'

if ($status != 0) then
    echo
    echo "ERROR: verification failed."
    echo
    echo "If MPI.versioninfo reports a binary other than system, the"
    echo "preference was not picked up. Confirm that MPIPreferences is a"
    echo "direct dependency of ${PROJECT} and re-run this script."
    echo
    echo "If a bundled MPI library is still loaded, the override did not take"
    echo "effect -- check the UUID and the OpenMPI key in:"
    echo "  ${OVERRIDES}"
    exit 1
endif

echo
echo "============================================================"
echo "Setup complete for the ${STACK} stack."
echo
echo "Interactive use, from the repository root:"
echo "  setenv JULIA_DEPOT_PATH ${DEPOT}"
echo "  module load ${COMPILER_MODULE}"
echo "  module load ${MPI_MODULE}"
echo "  julia ${JULIA_CHANNEL} --project=.buildkite ..."
echo
echo "Batch jobs must set the same depot and modules, and launch with:"
echo "  setenv PMIX_MCA_psec native"
echo "  setenv OMPI_MCA_pmix  ext3x"
echo "  srun --mpi=${SRUN_MPI} ..."
echo
echo "The two MCA settings only silence PMIx startup noise; the job runs"
echo "without them. --mpi=pmi2 does not work here, see ${STACKS_ENV}."
echo
echo "NOTE: .buildkite/LocalPreferences.toml is generated, not tracked in git,"
echo "and it is shared by every stack on every machine. Re-run this script"
echo "after working on another cluster."
echo "============================================================"
